name: Build Master Artifact

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Use Node.js 12.x
          uses: actions/setup-node@v1
          with:
            node-version: 12.x

        - run: npm install
        - run: npm run build  
          env:
            CI: true

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2
          with:
            path: build
